# Generated by Django 4.2.23 on 2025-09-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
    ]
