# Generated by Django 4.2.7 on 2026-03-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_active_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(choices=[(1.0, '1 Star'), (1.5, '1.5 Stars'), (2.0, '2 Stars'), (2.5, '2.5 Stars'), (3.0, '3 Stars'), (3.5, '3.5 Stars'), (4.0, '4 Stars'), (4.5, '4.5 Stars'), (5.0, '5 Stars')], decimal_places=1, max_digits=2),
        ),
    ]
