# Generated by Django 4.2.7 on 2026-03-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, help_text='Official product release date (used for time-decay ranking)', null=True),
        ),
    ]
