# Generated by Django 4.2.7 on 2026-04-07 03:46

from django.db import migrations
import pgvector.django
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_created_at_alter_product_price'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, help_text='Product embeddings for Semantic AI search', null=True),
        ),
    ]
